//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class openMICDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.openMICData>
    {
    
        public openMICDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).openMICData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class openMICDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.openMICData>
    {
        public openMICDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DefaultValue> DefaultValueCount()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DefaultValue> query;
            query = this.GetQuery<global::LightSwitchApplication.Implementation.DefaultValue>("DefaultValues");
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.AccessLog))
            {
                return new global::LightSwitchApplication.Implementation.AccessLog();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.AlarmLog))
            {
                return new global::LightSwitchApplication.Implementation.AlarmLog();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Alarm))
            {
                return new global::LightSwitchApplication.Implementation.Alarm();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.AuditLog))
            {
                return new global::LightSwitchApplication.Implementation.AuditLog();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Company))
            {
                return new global::LightSwitchApplication.Implementation.Company();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DefaultValue))
            {
                return new global::LightSwitchApplication.Implementation.DefaultValue();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Device))
            {
                return new global::LightSwitchApplication.Implementation.Device();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ErrorLog))
            {
                return new global::LightSwitchApplication.Implementation.ErrorLog();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Historian))
            {
                return new global::LightSwitchApplication.Implementation.Historian();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Interconnection))
            {
                return new global::LightSwitchApplication.Implementation.Interconnection();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Measurement))
            {
                return new global::LightSwitchApplication.Implementation.Measurement();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Node))
            {
                return new global::LightSwitchApplication.Implementation.Node();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Protocol))
            {
                return new global::LightSwitchApplication.Implementation.Protocol();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.SignalType))
            {
                return new global::LightSwitchApplication.Implementation.SignalType();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Statistic))
            {
                return new global::LightSwitchApplication.Implementation.Statistic();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.VendorDevice))
            {
                return new global::LightSwitchApplication.Implementation.VendorDevice();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Vendor))
            {
                return new global::LightSwitchApplication.Implementation.Vendor();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.openMICData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.openMICData(this.GetEntityConnectionString(
                "openMICData",
                "res://" + assemblyName + "/openMICData.csdl|res://" + assemblyName + "/openMICData.ssdl|res://" + assemblyName + "/openMICData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.AccessLog))
            {
                return new global::LightSwitchApplication.Implementation.AccessLog();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AlarmLog))
            {
                return new global::LightSwitchApplication.Implementation.AlarmLog();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Alarm))
            {
                return new global::LightSwitchApplication.Implementation.Alarm();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AuditLog))
            {
                return new global::LightSwitchApplication.Implementation.AuditLog();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Company))
            {
                return new global::LightSwitchApplication.Implementation.Company();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DefaultValue))
            {
                return new global::LightSwitchApplication.Implementation.DefaultValue();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Device))
            {
                return new global::LightSwitchApplication.Implementation.Device();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ErrorLog))
            {
                return new global::LightSwitchApplication.Implementation.ErrorLog();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Historian))
            {
                return new global::LightSwitchApplication.Implementation.Historian();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Interconnection))
            {
                return new global::LightSwitchApplication.Implementation.Interconnection();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Measurement))
            {
                return new global::LightSwitchApplication.Implementation.Measurement();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Node))
            {
                return new global::LightSwitchApplication.Implementation.Node();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Protocol))
            {
                return new global::LightSwitchApplication.Implementation.Protocol();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SignalType))
            {
                return new global::LightSwitchApplication.Implementation.SignalType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Statistic))
            {
                return new global::LightSwitchApplication.Implementation.Statistic();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.VendorDevice))
            {
                return new global::LightSwitchApplication.Implementation.VendorDevice();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Vendor))
            {
                return new global::LightSwitchApplication.Implementation.Vendor();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.openMICDataService))
            {
                return new global::LightSwitchApplication.openMICDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.openMICDataService))
            {
                return new global::LightSwitchApplication.Implementation.openMICDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.AccessLog) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AccessLog);
            }
            if (typeof(global::LightSwitchApplication.AlarmLog) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AlarmLog);
            }
            if (typeof(global::LightSwitchApplication.Alarm) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Alarm);
            }
            if (typeof(global::LightSwitchApplication.AuditLog) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AuditLog);
            }
            if (typeof(global::LightSwitchApplication.Company) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Company);
            }
            if (typeof(global::LightSwitchApplication.DefaultValue) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DefaultValue);
            }
            if (typeof(global::LightSwitchApplication.Device) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Device);
            }
            if (typeof(global::LightSwitchApplication.ErrorLog) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ErrorLog);
            }
            if (typeof(global::LightSwitchApplication.Historian) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Historian);
            }
            if (typeof(global::LightSwitchApplication.Interconnection) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Interconnection);
            }
            if (typeof(global::LightSwitchApplication.Measurement) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Measurement);
            }
            if (typeof(global::LightSwitchApplication.Node) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Node);
            }
            if (typeof(global::LightSwitchApplication.Protocol) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Protocol);
            }
            if (typeof(global::LightSwitchApplication.SignalType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SignalType);
            }
            if (typeof(global::LightSwitchApplication.Statistic) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Statistic);
            }
            if (typeof(global::LightSwitchApplication.VendorDevice) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.VendorDevice);
            }
            if (typeof(global::LightSwitchApplication.Vendor) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Vendor);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AccessLog :
        global::LightSwitchApplication.AccessLog.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AlarmLog :
        global::LightSwitchApplication.AlarmLog.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AlarmLog.DetailsClass.IImplementation.Alarm
        {
            get
            {
                return this.Alarm;
            }
            set
            {
                this.Alarm = (global::LightSwitchApplication.Implementation.Alarm)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Alarm");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AlarmLog.DetailsClass.IImplementation.Alarm1
        {
            get
            {
                return this.Alarm1;
            }
            set
            {
                this.Alarm1 = (global::LightSwitchApplication.Implementation.Alarm)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Alarm1");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AlarmLog.DetailsClass.IImplementation.Measurement
        {
            get
            {
                return this.Measurement;
            }
            set
            {
                this.Measurement = (global::LightSwitchApplication.Implementation.Measurement)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Measurement");
                }
            }
        }
        
        partial void OnNewStateChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Alarm");
            }
        }
        
        partial void OnPreviousStateChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Alarm1");
            }
        }
        
        partial void OnSignalIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Measurement");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Alarm :
        global::LightSwitchApplication.Alarm.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Alarm.DetailsClass.IImplementation.Measurement
        {
            get
            {
                return this.Measurement;
            }
            set
            {
                this.Measurement = (global::LightSwitchApplication.Implementation.Measurement)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Measurement");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Alarm.DetailsClass.IImplementation.Node
        {
            get
            {
                return this.Node;
            }
            set
            {
                this.Node = (global::LightSwitchApplication.Implementation.Node)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Node");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Alarm.DetailsClass.IImplementation.AlarmLogs
        {
            get
            {
                return this.AlarmLogs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Alarm.DetailsClass.IImplementation.AlarmLogs1
        {
            get
            {
                return this.AlarmLogs1;
            }
        }
        
        partial void OnSignalIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Measurement");
            }
        }
        
        partial void OnNodeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Node");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AuditLog :
        global::LightSwitchApplication.AuditLog.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Company :
        global::LightSwitchApplication.Company.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Company.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Company.DetailsClass.IImplementation.Nodes
        {
            get
            {
                return this.Nodes;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Company.DetailsClass.IImplementation.DefaultValues
        {
            get
            {
                return this.DefaultValues;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DefaultValue :
        global::LightSwitchApplication.DefaultValue.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DefaultValue.DetailsClass.IImplementation.Company
        {
            get
            {
                return this.Company;
            }
            set
            {
                this.Company = (global::LightSwitchApplication.Implementation.Company)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Company");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DefaultValue.DetailsClass.IImplementation.Historian
        {
            get
            {
                return this.Historian;
            }
            set
            {
                this.Historian = (global::LightSwitchApplication.Implementation.Historian)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Historian");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DefaultValue.DetailsClass.IImplementation.Interconnection
        {
            get
            {
                return this.Interconnection;
            }
            set
            {
                this.Interconnection = (global::LightSwitchApplication.Implementation.Interconnection)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Interconnection");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.DefaultValue.DetailsClass.IImplementation.Node
        {
            get
            {
                return this.Node;
            }
            set
            {
                this.Node = (global::LightSwitchApplication.Implementation.Node)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Node");
                }
            }
        }
        
        partial void OnCompanyIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Company");
            }
        }
        
        partial void OnHistorianIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Historian");
            }
        }
        
        partial void OnInterconnectionIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Interconnection");
            }
        }
        
        partial void OnNodeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Node");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Device :
        global::LightSwitchApplication.Device.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.Interconnection
        {
            get
            {
                return this.Interconnection;
            }
            set
            {
                this.Interconnection = (global::LightSwitchApplication.Implementation.Interconnection)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Interconnection");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.Node
        {
            get
            {
                return this.Node;
            }
            set
            {
                this.Node = (global::LightSwitchApplication.Implementation.Node)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Node");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.Protocol
        {
            get
            {
                return this.Protocol;
            }
            set
            {
                this.Protocol = (global::LightSwitchApplication.Implementation.Protocol)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Protocol");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.VendorDevice
        {
            get
            {
                return this.VendorDevice;
            }
            set
            {
                this.VendorDevice = (global::LightSwitchApplication.Implementation.VendorDevice)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("VendorDevice");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Device.DetailsClass.IImplementation.Measurements
        {
            get
            {
                return this.Measurements;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.Historian
        {
            get
            {
                return this.Historian;
            }
            set
            {
                this.Historian = (global::LightSwitchApplication.Implementation.Historian)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Historian");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Device.DetailsClass.IImplementation.Company
        {
            get
            {
                return this.Company;
            }
            set
            {
                this.Company = (global::LightSwitchApplication.Implementation.Company)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Company");
                }
            }
        }
        
        partial void OnInterconnectionIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Interconnection");
            }
        }
        
        partial void OnNodeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Node");
            }
        }
        
        partial void OnProtocolIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Protocol");
            }
        }
        
        partial void OnVendorDeviceIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("VendorDevice");
            }
        }
        
        partial void OnHistorianIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Historian");
            }
        }
        
        partial void OnCompanyIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Company");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ErrorLog :
        global::LightSwitchApplication.ErrorLog.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Historian :
        global::LightSwitchApplication.Historian.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Historian.DetailsClass.IImplementation.Node
        {
            get
            {
                return this.Node;
            }
            set
            {
                this.Node = (global::LightSwitchApplication.Implementation.Node)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Node");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Historian.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Historian.DetailsClass.IImplementation.DefaultValues
        {
            get
            {
                return this.DefaultValues;
            }
        }
        
        partial void OnNodeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Node");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Interconnection :
        global::LightSwitchApplication.Interconnection.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Interconnection.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Interconnection.DetailsClass.IImplementation.DefaultValues
        {
            get
            {
                return this.DefaultValues;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Measurement :
        global::LightSwitchApplication.Measurement.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Measurement.DetailsClass.IImplementation.Alarms
        {
            get
            {
                return this.Alarms;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Measurement.DetailsClass.IImplementation.AlarmLogs
        {
            get
            {
                return this.AlarmLogs;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Measurement.DetailsClass.IImplementation.Device
        {
            get
            {
                return this.Device;
            }
            set
            {
                this.Device = (global::LightSwitchApplication.Implementation.Device)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Device");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Measurement.DetailsClass.IImplementation.SignalType
        {
            get
            {
                return this.SignalType;
            }
            set
            {
                this.SignalType = (global::LightSwitchApplication.Implementation.SignalType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("SignalType");
                }
            }
        }
        
        partial void OnDeviceIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Device");
            }
        }
        
        partial void OnSignalTypeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("SignalType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Node :
        global::LightSwitchApplication.Node.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Node.DetailsClass.IImplementation.Alarms
        {
            get
            {
                return this.Alarms;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Node.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Node.DetailsClass.IImplementation.Historians
        {
            get
            {
                return this.Historians;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Node.DetailsClass.IImplementation.Company
        {
            get
            {
                return this.Company;
            }
            set
            {
                this.Company = (global::LightSwitchApplication.Implementation.Company)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Company");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Node.DetailsClass.IImplementation.DefaultValues
        {
            get
            {
                return this.DefaultValues;
            }
        }
        
        partial void OnCompanyIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Company");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Protocol :
        global::LightSwitchApplication.Protocol.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Protocol.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SignalType :
        global::LightSwitchApplication.SignalType.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.SignalType.DetailsClass.IImplementation.Measurements
        {
            get
            {
                return this.Measurements;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Statistic :
        global::LightSwitchApplication.Statistic.DetailsClass.IImplementation
    {
    
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class VendorDevice :
        global::LightSwitchApplication.VendorDevice.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.VendorDevice.DetailsClass.IImplementation.Devices
        {
            get
            {
                return this.Devices;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.VendorDevice.DetailsClass.IImplementation.Vendor
        {
            get
            {
                return this.Vendor;
            }
            set
            {
                this.Vendor = (global::LightSwitchApplication.Implementation.Vendor)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        partial void OnVendorIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Vendor");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Vendor :
        global::LightSwitchApplication.Vendor.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Vendor.DetailsClass.IImplementation.VendorDevices
        {
            get
            {
                return this.VendorDevices;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

