

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class Statistic : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Statistic entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Statistic()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Statistic(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Statistic> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Statistic.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Statistic_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Statistic_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Source
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Source);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Source, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Source_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Source_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Source_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int SignalIndex
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.SignalIndex);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.SignalIndex, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SignalIndex_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SignalIndex_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SignalIndex_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AssemblyName
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.AssemblyName);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.AssemblyName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssemblyName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssemblyName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AssemblyName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TypeName
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.TypeName);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.TypeName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TypeName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TypeName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TypeName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MethodName
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.MethodName);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.MethodName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MethodName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MethodName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MethodName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Arguments
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Arguments);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Arguments, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Arguments_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Arguments_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Arguments_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool Enabled
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Enabled);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Enabled, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enabled_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enabled_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Enabled_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DataType
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.DataType);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.DataType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DataType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DisplayFormat
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.DisplayFormat);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.DisplayFormat, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DisplayFormat_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DisplayFormat_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DisplayFormat_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsConnectedState
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.IsConnectedState);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.IsConnectedState, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsConnectedState_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsConnectedState_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsConnectedState_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int LoadOrder
        {
            get
            {
                return global::LightSwitchApplication.Statistic.DetailsClass.GetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.LoadOrder);
            }
            set
            {
                global::LightSwitchApplication.Statistic.DetailsClass.SetValue(this, global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.LoadOrder, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadOrder_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadOrder_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadOrder_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Statistic,
                global::LightSwitchApplication.Statistic.DetailsClass,
                global::LightSwitchApplication.Statistic.DetailsClass.IImplementation,
                global::LightSwitchApplication.Statistic.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass>.Entry
                __StatisticEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass>.Entry(
                    global::LightSwitchApplication.Statistic.DetailsClass.__Statistic_CreateNew,
                    global::LightSwitchApplication.Statistic.DetailsClass.__Statistic_Created,
                    global::LightSwitchApplication.Statistic.DetailsClass.__Statistic_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Statistic __Statistic_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Statistic> es)
            {
                return new global::LightSwitchApplication.Statistic(es);
            }
            private static void __Statistic_Created(global::LightSwitchApplication.Statistic e)
            {
                e.Statistic_Created();
            }
            private static bool __Statistic_AllowSaveWithErrors(global::LightSwitchApplication.Statistic e)
            {
                bool result = false;
                e.Statistic_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Statistic.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> Source
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Source) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int> SignalIndex
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.SignalIndex) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> AssemblyName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.AssemblyName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> TypeName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.TypeName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> MethodName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.MethodName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> Arguments
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Arguments) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool> Enabled
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.Enabled) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> DataType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.DataType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string> DisplayFormat
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.DisplayFormat) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool> IsConnectedState
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.IsConnectedState) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int> LoadOrder
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties.LoadOrder) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string Source { get; set; }
                new int SignalIndex { get; set; }
                new string Name { get; set; }
                new string Description { get; set; }
                new string AssemblyName { get; set; }
                new string TypeName { get; set; }
                new string MethodName { get; set; }
                new string Arguments { get; set; }
                new bool Enabled { get; set; }
                new string DataType { get; set; }
                new string DisplayFormat { get; set; }
                new bool IsConnectedState { get; set; }
                new int LoadOrder { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    Source = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "Source",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Source_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Source_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Source_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Source_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Source_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Source_OnValueChanged);
                private static void _Source_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._Source, sf);
                }
                private static bool _Source_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.Source_IsReadOnly(ref result);
                    return result;
                }
                private static void _Source_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Source_Validate(r);
                }
                private static string _Source_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.Source;
                }
                private static void _Source_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Source = v;
                }
                private static void _Source_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.Source_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Entry
                    SignalIndex = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Entry(
                        "SignalIndex",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._SignalIndex_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._SignalIndex_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._SignalIndex_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._SignalIndex_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._SignalIndex_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._SignalIndex_OnValueChanged);
                private static void _SignalIndex_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._SignalIndex, sf);
                }
                private static bool _SignalIndex_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.SignalIndex_IsReadOnly(ref result);
                    return result;
                }
                private static void _SignalIndex_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SignalIndex_Validate(r);
                }
                private static int _SignalIndex_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.SignalIndex;
                }
                private static void _SignalIndex_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, int v)
                {
                    d.ImplementationEntity.SignalIndex = v;
                }
                private static void _SignalIndex_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.SignalIndex_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    AssemblyName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "AssemblyName",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._AssemblyName_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._AssemblyName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._AssemblyName_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._AssemblyName_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._AssemblyName_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._AssemblyName_OnValueChanged);
                private static void _AssemblyName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._AssemblyName, sf);
                }
                private static bool _AssemblyName_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.AssemblyName_IsReadOnly(ref result);
                    return result;
                }
                private static void _AssemblyName_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AssemblyName_Validate(r);
                }
                private static string _AssemblyName_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.AssemblyName;
                }
                private static void _AssemblyName_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.AssemblyName = v;
                }
                private static void _AssemblyName_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.AssemblyName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    TypeName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "TypeName",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._TypeName_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._TypeName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._TypeName_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._TypeName_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._TypeName_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._TypeName_OnValueChanged);
                private static void _TypeName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._TypeName, sf);
                }
                private static bool _TypeName_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.TypeName_IsReadOnly(ref result);
                    return result;
                }
                private static void _TypeName_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TypeName_Validate(r);
                }
                private static string _TypeName_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.TypeName;
                }
                private static void _TypeName_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TypeName = v;
                }
                private static void _TypeName_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.TypeName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    MethodName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "MethodName",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._MethodName_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._MethodName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._MethodName_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._MethodName_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._MethodName_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._MethodName_OnValueChanged);
                private static void _MethodName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._MethodName, sf);
                }
                private static bool _MethodName_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.MethodName_IsReadOnly(ref result);
                    return result;
                }
                private static void _MethodName_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MethodName_Validate(r);
                }
                private static string _MethodName_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.MethodName;
                }
                private static void _MethodName_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MethodName = v;
                }
                private static void _MethodName_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.MethodName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    Arguments = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "Arguments",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Arguments_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Arguments_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Arguments_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Arguments_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Arguments_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Arguments_OnValueChanged);
                private static void _Arguments_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._Arguments, sf);
                }
                private static bool _Arguments_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.Arguments_IsReadOnly(ref result);
                    return result;
                }
                private static void _Arguments_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Arguments_Validate(r);
                }
                private static string _Arguments_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.Arguments;
                }
                private static void _Arguments_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Arguments = v;
                }
                private static void _Arguments_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.Arguments_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Entry
                    Enabled = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Entry(
                        "Enabled",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Enabled_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Enabled_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Enabled_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Enabled_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Enabled_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._Enabled_OnValueChanged);
                private static void _Enabled_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._Enabled, sf);
                }
                private static bool _Enabled_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.Enabled_IsReadOnly(ref result);
                    return result;
                }
                private static void _Enabled_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Enabled_Validate(r);
                }
                private static bool _Enabled_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.Enabled;
                }
                private static void _Enabled_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.Enabled = v;
                }
                private static void _Enabled_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.Enabled_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    DataType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "DataType",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DataType_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DataType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DataType_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DataType_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DataType_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DataType_OnValueChanged);
                private static void _DataType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._DataType, sf);
                }
                private static bool _DataType_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.DataType_IsReadOnly(ref result);
                    return result;
                }
                private static void _DataType_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DataType_Validate(r);
                }
                private static string _DataType_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.DataType;
                }
                private static void _DataType_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DataType = v;
                }
                private static void _DataType_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.DataType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry
                    DisplayFormat = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Entry(
                        "DisplayFormat",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DisplayFormat_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DisplayFormat_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DisplayFormat_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DisplayFormat_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DisplayFormat_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._DisplayFormat_OnValueChanged);
                private static void _DisplayFormat_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._DisplayFormat, sf);
                }
                private static bool _DisplayFormat_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.DisplayFormat_IsReadOnly(ref result);
                    return result;
                }
                private static void _DisplayFormat_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DisplayFormat_Validate(r);
                }
                private static string _DisplayFormat_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.DisplayFormat;
                }
                private static void _DisplayFormat_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DisplayFormat = v;
                }
                private static void _DisplayFormat_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.DisplayFormat_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Entry
                    IsConnectedState = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Entry(
                        "IsConnectedState",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._IsConnectedState_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._IsConnectedState_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._IsConnectedState_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._IsConnectedState_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._IsConnectedState_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._IsConnectedState_OnValueChanged);
                private static void _IsConnectedState_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._IsConnectedState, sf);
                }
                private static bool _IsConnectedState_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.IsConnectedState_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsConnectedState_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsConnectedState_Validate(r);
                }
                private static bool _IsConnectedState_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.IsConnectedState;
                }
                private static void _IsConnectedState_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsConnectedState = v;
                }
                private static void _IsConnectedState_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.IsConnectedState_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Entry
                    LoadOrder = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Entry(
                        "LoadOrder",
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._LoadOrder_Stub,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._LoadOrder_ComputeIsReadOnly,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._LoadOrder_Validate,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._LoadOrder_GetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._LoadOrder_SetImplementationValue,
                        global::LightSwitchApplication.Statistic.DetailsClass.PropertySetProperties._LoadOrder_OnValueChanged);
                private static void _LoadOrder_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Statistic.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Data> c, global::LightSwitchApplication.Statistic.DetailsClass d, object sf)
                {
                    c(d, ref d._LoadOrder, sf);
                }
                private static bool _LoadOrder_ComputeIsReadOnly(global::LightSwitchApplication.Statistic e)
                {
                    bool result = false;
                    e.LoadOrder_IsReadOnly(ref result);
                    return result;
                }
                private static void _LoadOrder_Validate(global::LightSwitchApplication.Statistic e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LoadOrder_Validate(r);
                }
                private static int _LoadOrder_GetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d)
                {
                    return d.ImplementationEntity.LoadOrder;
                }
                private static void _LoadOrder_SetImplementationValue(global::LightSwitchApplication.Statistic.DetailsClass d, int v)
                {
                    d.ImplementationEntity.LoadOrder = v;
                }
                private static void _LoadOrder_OnValueChanged(global::LightSwitchApplication.Statistic e)
                {
                    e.LoadOrder_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _Source;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Data _SignalIndex;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _AssemblyName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _TypeName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _MethodName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _Arguments;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Data _Enabled;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _DataType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, string>.Data _DisplayFormat;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, bool>.Data _IsConnectedState;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Statistic, global::LightSwitchApplication.Statistic.DetailsClass, int>.Data _LoadOrder;
            
        }
    
        #endregion
    }
    
    #endregion
}
