

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class ErrorLog : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ErrorLog entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ErrorLog()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ErrorLog(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ErrorLog> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ErrorLog.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorLog_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ErrorLog_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.ErrorLog.DetailsClass.GetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Source
        {
            get
            {
                return global::LightSwitchApplication.ErrorLog.DetailsClass.GetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Source);
            }
            set
            {
                global::LightSwitchApplication.ErrorLog.DetailsClass.SetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Source, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Source_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Source_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Source_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Type
        {
            get
            {
                return global::LightSwitchApplication.ErrorLog.DetailsClass.GetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Type);
            }
            set
            {
                global::LightSwitchApplication.ErrorLog.DetailsClass.SetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Type, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Type_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Type_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Type_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Message
        {
            get
            {
                return global::LightSwitchApplication.ErrorLog.DetailsClass.GetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Message);
            }
            set
            {
                global::LightSwitchApplication.ErrorLog.DetailsClass.SetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Message, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Message_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Detail
        {
            get
            {
                return global::LightSwitchApplication.ErrorLog.DetailsClass.GetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Detail);
            }
            set
            {
                global::LightSwitchApplication.ErrorLog.DetailsClass.SetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Detail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Detail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime CreatedOn
        {
            get
            {
                return global::LightSwitchApplication.ErrorLog.DetailsClass.GetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.CreatedOn);
            }
            set
            {
                global::LightSwitchApplication.ErrorLog.DetailsClass.SetValue(this, global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.CreatedOn, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedOn_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedOn_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedOn_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ErrorLog,
                global::LightSwitchApplication.ErrorLog.DetailsClass,
                global::LightSwitchApplication.ErrorLog.DetailsClass.IImplementation,
                global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass>.Entry
                __ErrorLogEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass>.Entry(
                    global::LightSwitchApplication.ErrorLog.DetailsClass.__ErrorLog_CreateNew,
                    global::LightSwitchApplication.ErrorLog.DetailsClass.__ErrorLog_Created,
                    global::LightSwitchApplication.ErrorLog.DetailsClass.__ErrorLog_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ErrorLog __ErrorLog_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ErrorLog> es)
            {
                return new global::LightSwitchApplication.ErrorLog(es);
            }
            private static void __ErrorLog_Created(global::LightSwitchApplication.ErrorLog e)
            {
                e.ErrorLog_Created();
            }
            private static bool __ErrorLog_AllowSaveWithErrors(global::LightSwitchApplication.ErrorLog e)
            {
                bool result = false;
                e.ErrorLog_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string> Source
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Source) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string> Type
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Type) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string> Message
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Message) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string> Detail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.Detail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, global::System.DateTime> CreatedOn
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties.CreatedOn) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, global::System.DateTime>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string Source { get; set; }
                new string Type { get; set; }
                new string Message { get; set; }
                new string Detail { get; set; }
                new global::System.DateTime CreatedOn { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ErrorLog.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, int>.Data> c, global::LightSwitchApplication.ErrorLog.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.ErrorLog e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.ErrorLog e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.ErrorLog e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry
                    Source = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry(
                        "Source",
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Source_Stub,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Source_ComputeIsReadOnly,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Source_Validate,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Source_GetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Source_SetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Source_OnValueChanged);
                private static void _Source_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ErrorLog.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data> c, global::LightSwitchApplication.ErrorLog.DetailsClass d, object sf)
                {
                    c(d, ref d._Source, sf);
                }
                private static bool _Source_ComputeIsReadOnly(global::LightSwitchApplication.ErrorLog e)
                {
                    bool result = false;
                    e.Source_IsReadOnly(ref result);
                    return result;
                }
                private static void _Source_Validate(global::LightSwitchApplication.ErrorLog e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Source_Validate(r);
                }
                private static string _Source_GetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d)
                {
                    return d.ImplementationEntity.Source;
                }
                private static void _Source_SetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Source = v;
                }
                private static void _Source_OnValueChanged(global::LightSwitchApplication.ErrorLog e)
                {
                    e.Source_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry
                    Type = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry(
                        "Type",
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Type_Stub,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Type_ComputeIsReadOnly,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Type_Validate,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Type_GetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Type_SetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Type_OnValueChanged);
                private static void _Type_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ErrorLog.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data> c, global::LightSwitchApplication.ErrorLog.DetailsClass d, object sf)
                {
                    c(d, ref d._Type, sf);
                }
                private static bool _Type_ComputeIsReadOnly(global::LightSwitchApplication.ErrorLog e)
                {
                    bool result = false;
                    e.Type_IsReadOnly(ref result);
                    return result;
                }
                private static void _Type_Validate(global::LightSwitchApplication.ErrorLog e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Type_Validate(r);
                }
                private static string _Type_GetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d)
                {
                    return d.ImplementationEntity.Type;
                }
                private static void _Type_SetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Type = v;
                }
                private static void _Type_OnValueChanged(global::LightSwitchApplication.ErrorLog e)
                {
                    e.Type_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry
                    Message = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry(
                        "Message",
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Message_Stub,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Message_ComputeIsReadOnly,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Message_Validate,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Message_GetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Message_SetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Message_OnValueChanged);
                private static void _Message_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ErrorLog.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data> c, global::LightSwitchApplication.ErrorLog.DetailsClass d, object sf)
                {
                    c(d, ref d._Message, sf);
                }
                private static bool _Message_ComputeIsReadOnly(global::LightSwitchApplication.ErrorLog e)
                {
                    bool result = false;
                    e.Message_IsReadOnly(ref result);
                    return result;
                }
                private static void _Message_Validate(global::LightSwitchApplication.ErrorLog e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Message_Validate(r);
                }
                private static string _Message_GetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d)
                {
                    return d.ImplementationEntity.Message;
                }
                private static void _Message_SetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Message = v;
                }
                private static void _Message_OnValueChanged(global::LightSwitchApplication.ErrorLog e)
                {
                    e.Message_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry
                    Detail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Entry(
                        "Detail",
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Detail_Stub,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Detail_ComputeIsReadOnly,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Detail_Validate,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Detail_GetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Detail_SetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._Detail_OnValueChanged);
                private static void _Detail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ErrorLog.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data> c, global::LightSwitchApplication.ErrorLog.DetailsClass d, object sf)
                {
                    c(d, ref d._Detail, sf);
                }
                private static bool _Detail_ComputeIsReadOnly(global::LightSwitchApplication.ErrorLog e)
                {
                    bool result = false;
                    e.Detail_IsReadOnly(ref result);
                    return result;
                }
                private static void _Detail_Validate(global::LightSwitchApplication.ErrorLog e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Detail_Validate(r);
                }
                private static string _Detail_GetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d)
                {
                    return d.ImplementationEntity.Detail;
                }
                private static void _Detail_SetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Detail = v;
                }
                private static void _Detail_OnValueChanged(global::LightSwitchApplication.ErrorLog e)
                {
                    e.Detail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, global::System.DateTime>.Entry
                    CreatedOn = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, global::System.DateTime>.Entry(
                        "CreatedOn",
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._CreatedOn_Stub,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._CreatedOn_ComputeIsReadOnly,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._CreatedOn_Validate,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._CreatedOn_GetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._CreatedOn_SetImplementationValue,
                        global::LightSwitchApplication.ErrorLog.DetailsClass.PropertySetProperties._CreatedOn_OnValueChanged);
                private static void _CreatedOn_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ErrorLog.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ErrorLog.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedOn, sf);
                }
                private static bool _CreatedOn_ComputeIsReadOnly(global::LightSwitchApplication.ErrorLog e)
                {
                    bool result = false;
                    e.CreatedOn_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedOn_Validate(global::LightSwitchApplication.ErrorLog e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedOn_Validate(r);
                }
                private static global::System.DateTime _CreatedOn_GetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedOn;
                }
                private static void _CreatedOn_SetImplementationValue(global::LightSwitchApplication.ErrorLog.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.CreatedOn = global::LightSwitchApplication.ErrorLog.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedOn_OnValueChanged(global::LightSwitchApplication.ErrorLog e)
                {
                    e.CreatedOn_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data _Source;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data _Type;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data _Message;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, string>.Data _Detail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ErrorLog, global::LightSwitchApplication.ErrorLog.DetailsClass, global::System.DateTime>.Data _CreatedOn;
            
        }
    
        #endregion
    }
    
    #endregion
}
