

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class DefaultValue : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the DefaultValue entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DefaultValue()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DefaultValue(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DefaultValue> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.DefaultValue.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DefaultValue_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DefaultValue_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.DefaultValue.DetailsClass.GetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.ID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ContactList
        {
            get
            {
                return global::LightSwitchApplication.DefaultValue.DetailsClass.GetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.ContactList);
            }
            set
            {
                global::LightSwitchApplication.DefaultValue.DetailsClass.SetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.ContactList, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContactList_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Company Company
        {
            get
            {
                return global::LightSwitchApplication.DefaultValue.DetailsClass.GetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Company);
            }
            set
            {
                global::LightSwitchApplication.DefaultValue.DetailsClass.SetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Company, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Company_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Historian Historian
        {
            get
            {
                return global::LightSwitchApplication.DefaultValue.DetailsClass.GetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Historian);
            }
            set
            {
                global::LightSwitchApplication.DefaultValue.DetailsClass.SetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Historian, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Historian_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Historian_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Historian_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Interconnection Interconnection
        {
            get
            {
                return global::LightSwitchApplication.DefaultValue.DetailsClass.GetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Interconnection);
            }
            set
            {
                global::LightSwitchApplication.DefaultValue.DetailsClass.SetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Interconnection, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interconnection_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interconnection_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Interconnection_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Node Node
        {
            get
            {
                return global::LightSwitchApplication.DefaultValue.DetailsClass.GetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Node);
            }
            set
            {
                global::LightSwitchApplication.DefaultValue.DetailsClass.SetValue(this, global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Node, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Node_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Node_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Node_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.DefaultValue,
                global::LightSwitchApplication.DefaultValue.DetailsClass,
                global::LightSwitchApplication.DefaultValue.DetailsClass.IImplementation,
                global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass>.Entry
                __DefaultValueEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass>.Entry(
                    global::LightSwitchApplication.DefaultValue.DetailsClass.__DefaultValue_CreateNew,
                    global::LightSwitchApplication.DefaultValue.DetailsClass.__DefaultValue_Created,
                    global::LightSwitchApplication.DefaultValue.DetailsClass.__DefaultValue_AllowSaveWithErrors);
            private static global::LightSwitchApplication.DefaultValue __DefaultValue_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DefaultValue> es)
            {
                return new global::LightSwitchApplication.DefaultValue(es);
            }
            private static void __DefaultValue_Created(global::LightSwitchApplication.DefaultValue e)
            {
                e.DefaultValue_Created();
            }
            private static bool __DefaultValue_AllowSaveWithErrors(global::LightSwitchApplication.DefaultValue e)
            {
                bool result = false;
                e.DefaultValue_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, string> ContactList
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.ContactList) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Company> Company
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Company) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Company>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Historian> Historian
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Historian) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Historian>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Interconnection> Interconnection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Interconnection) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Interconnection>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Node> Node
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Node) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Node>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; }
                new string ContactList { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Company { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Historian { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Interconnection { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Node { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DefaultValue.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, int>.Data> c, global::LightSwitchApplication.DefaultValue.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.DefaultValue e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.DefaultValue e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.DefaultValue e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, string>.Entry
                    ContactList = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, string>.Entry(
                        "ContactList",
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ContactList_Stub,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ContactList_ComputeIsReadOnly,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ContactList_Validate,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ContactList_GetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ContactList_SetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._ContactList_OnValueChanged);
                private static void _ContactList_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DefaultValue.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, string>.Data> c, global::LightSwitchApplication.DefaultValue.DetailsClass d, object sf)
                {
                    c(d, ref d._ContactList, sf);
                }
                private static bool _ContactList_ComputeIsReadOnly(global::LightSwitchApplication.DefaultValue e)
                {
                    bool result = false;
                    e.ContactList_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContactList_Validate(global::LightSwitchApplication.DefaultValue e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContactList_Validate(r);
                }
                private static string _ContactList_GetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.ImplementationEntity.ContactList;
                }
                private static void _ContactList_SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ContactList = v;
                }
                private static void _ContactList_OnValueChanged(global::LightSwitchApplication.DefaultValue e)
                {
                    e.ContactList_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Company>.Entry
                    Company = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Company>.Entry(
                        "Company",
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_Stub,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_ComputeIsReadOnly,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_Validate,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_GetCoreImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_GetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_SetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_Refresh,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Company_OnValueChanged);
                private static void _Company_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DefaultValue.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Company>.Data> c, global::LightSwitchApplication.DefaultValue.DetailsClass d, object sf)
                {
                    c(d, ref d._Company, sf);
                }
                private static bool _Company_ComputeIsReadOnly(global::LightSwitchApplication.DefaultValue e)
                {
                    bool result = false;
                    e.Company_IsReadOnly(ref result);
                    return result;
                }
                private static void _Company_Validate(global::LightSwitchApplication.DefaultValue e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Company_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Company_GetCoreImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.ImplementationEntity.Company;
                }
                private static global::LightSwitchApplication.Company _Company_GetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Company, global::LightSwitchApplication.Company.DetailsClass>(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Company, ref d._Company);
                }
                private static void _Company_SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d, global::LightSwitchApplication.Company v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Company, ref d._Company, (i, ev) => i.Company = ev, v);
                }
                private static void _Company_Refresh(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Company, ref d._Company);
                }
                private static void _Company_OnValueChanged(global::LightSwitchApplication.DefaultValue e)
                {
                    e.Company_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Historian>.Entry
                    Historian = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Historian>.Entry(
                        "Historian",
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_Stub,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_ComputeIsReadOnly,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_Validate,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_GetCoreImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_GetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_SetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_Refresh,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Historian_OnValueChanged);
                private static void _Historian_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DefaultValue.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Historian>.Data> c, global::LightSwitchApplication.DefaultValue.DetailsClass d, object sf)
                {
                    c(d, ref d._Historian, sf);
                }
                private static bool _Historian_ComputeIsReadOnly(global::LightSwitchApplication.DefaultValue e)
                {
                    bool result = false;
                    e.Historian_IsReadOnly(ref result);
                    return result;
                }
                private static void _Historian_Validate(global::LightSwitchApplication.DefaultValue e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Historian_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Historian_GetCoreImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.ImplementationEntity.Historian;
                }
                private static global::LightSwitchApplication.Historian _Historian_GetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Historian, global::LightSwitchApplication.Historian.DetailsClass>(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Historian, ref d._Historian);
                }
                private static void _Historian_SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d, global::LightSwitchApplication.Historian v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Historian, ref d._Historian, (i, ev) => i.Historian = ev, v);
                }
                private static void _Historian_Refresh(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Historian, ref d._Historian);
                }
                private static void _Historian_OnValueChanged(global::LightSwitchApplication.DefaultValue e)
                {
                    e.Historian_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Interconnection>.Entry
                    Interconnection = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Interconnection>.Entry(
                        "Interconnection",
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_Stub,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_ComputeIsReadOnly,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_Validate,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_GetCoreImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_GetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_SetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_Refresh,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Interconnection_OnValueChanged);
                private static void _Interconnection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DefaultValue.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Interconnection>.Data> c, global::LightSwitchApplication.DefaultValue.DetailsClass d, object sf)
                {
                    c(d, ref d._Interconnection, sf);
                }
                private static bool _Interconnection_ComputeIsReadOnly(global::LightSwitchApplication.DefaultValue e)
                {
                    bool result = false;
                    e.Interconnection_IsReadOnly(ref result);
                    return result;
                }
                private static void _Interconnection_Validate(global::LightSwitchApplication.DefaultValue e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Interconnection_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Interconnection_GetCoreImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.ImplementationEntity.Interconnection;
                }
                private static global::LightSwitchApplication.Interconnection _Interconnection_GetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Interconnection, global::LightSwitchApplication.Interconnection.DetailsClass>(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Interconnection, ref d._Interconnection);
                }
                private static void _Interconnection_SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d, global::LightSwitchApplication.Interconnection v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Interconnection, ref d._Interconnection, (i, ev) => i.Interconnection = ev, v);
                }
                private static void _Interconnection_Refresh(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Interconnection, ref d._Interconnection);
                }
                private static void _Interconnection_OnValueChanged(global::LightSwitchApplication.DefaultValue e)
                {
                    e.Interconnection_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Node>.Entry
                    Node = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Node>.Entry(
                        "Node",
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_Stub,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_ComputeIsReadOnly,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_Validate,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_GetCoreImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_GetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_SetImplementationValue,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_Refresh,
                        global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties._Node_OnValueChanged);
                private static void _Node_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DefaultValue.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Node>.Data> c, global::LightSwitchApplication.DefaultValue.DetailsClass d, object sf)
                {
                    c(d, ref d._Node, sf);
                }
                private static bool _Node_ComputeIsReadOnly(global::LightSwitchApplication.DefaultValue e)
                {
                    bool result = false;
                    e.Node_IsReadOnly(ref result);
                    return result;
                }
                private static void _Node_Validate(global::LightSwitchApplication.DefaultValue e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Node_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Node_GetCoreImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.ImplementationEntity.Node;
                }
                private static global::LightSwitchApplication.Node _Node_GetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Node, global::LightSwitchApplication.Node.DetailsClass>(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Node, ref d._Node);
                }
                private static void _Node_SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass d, global::LightSwitchApplication.Node v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Node, ref d._Node, (i, ev) => i.Node = ev, v);
                }
                private static void _Node_Refresh(global::LightSwitchApplication.DefaultValue.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.DefaultValue.DetailsClass.PropertySetProperties.Node, ref d._Node);
                }
                private static void _Node_OnValueChanged(global::LightSwitchApplication.DefaultValue e)
                {
                    e.Node_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, string>.Data _ContactList;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Company>.Data _Company;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Historian>.Data _Historian;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Interconnection>.Data _Interconnection;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.DefaultValue, global::LightSwitchApplication.DefaultValue.DetailsClass, global::LightSwitchApplication.Node>.Data _Node;
            
        }
    
        #endregion
    }
    
    #endregion
}
